### ISSUE TITLE
port unholy engine to lemons

### ISSUE THREAD

**Issue by Sword352** [Unholywanderer/FNF-Unholy-Engine#7]
[Lemons](https://github.com/LemonsFramework/lemons) is an open source game framework made in Haxe.
It's plan is to show the world the true capabilities of HashLink by making a feature-rich game framework that can target many platforms, such as desktop, the web, and even consoles such as the PS3, the Wii U and the GameBoy, thanks to it's cross-platform APIs.

This project is suitable to be ported into Lemons.
Here are some advantages:

## Why should it be ported
good question well why not

## Advantages
free lemons 4 life

## Disadvantages
no more gogo.. no more gdto :cry:

More informations can be found in the [Lemons](https://plankdev.carrd.co/) website.

**Comment by libauror-a** [comment]
target platform correction, lemons by itself supports
- windows
- *nix
- haiku
lemons has no plans for release on the [wii u](https://www.youtube.com/c/scottthewoz) nor gameboy, though has plans for extra backend libraries, for the following platforms:
- windows 9x with lemons-9x
- ps3 with lemons-cell

**Comment by Sword352** [comment]
It seems the [Lemons](https://www.youtube.com/watch?v=dQw4w9WgXcQ) website does mention support for the Wii U and GameBoy. Was this an old plan that no longer applies today?

**Comment by Sword352** [comment]
It also states it's going to support [WebAssembly](https://store.steampowered.com/app/980610/Quaver/)

**Comment by charlesisfeline** [comment]
> It seems the [Lemons](https://www.youtube.com/watch?v=dQw4w9WgXcQ) website 

i swear i feel like i have memorized that link before

**Comment by CCobaltDev** [comment]
this is what github was meant for

pure satire
